### ISSUE TITLE
Use github releases

### ISSUE THREAD

**Issue by BrayanCaro** [Dialvive/SignaMundi-REST-API#26]
### Problem

Right now we use the latest commit of main as a reference to the stable version but we are not using a special tag.

### Suggestion

Use the semantic versioning, eg: `v1.2.3` to declare the version which we can be sure is stable.

![image](https://user-images.githubusercontent.com/41640423/134019948-03b96a40-3f96-4056-a0cb-0fb2fa0e8626.png)

We can click on `Create a new release` mannualy or we can use a workflow.

I've using [this](https://github.com/softprops/action-gh-release) pluging for that with the following `yml`:

There is a minimal example:

```
name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
```
That can read as _if someone pushes a tag, then create an automatic version release on github_
